services:
  webstore_sleuth_scrapoxy:
    image: scrapoxy/scrapoxy
    container_name: webstore_sleuth_scrapoxy
    ports:
      - 8888:8888
      - 8890:8890
    env_file:
      - .env
    volumes:
      - webstore_sleuth_scrapoxy_data:/cfg

volumes:
  webstore_sleuth_scrapoxy_data: